<?php
/**
 * @file
 * Drupal needs this blank file.
 */
/**
 * Implements hook_form_user_login_block_alter().
 */
function facebook_user_form_user_login_block_alter(&$form, &$form_state, $form_id) {
  //  dsm($form);
  $form['name']['#size'] = 20;
  $form['name']['#title'] = t('Email');
  $form['pass']['#size'] = 20;
  $markup = l(t('Forgotten account?'), 'user/password');
  $markup = '<div class="clearfix-login">' . $markup . '</div>';
  $form['links']['#markup'] = $markup;
  $form['links']['#weight'] = 100;
}

/**
* Implements hook_form_formID_alter().
*/
function facebook_user_form_user_register_form_alter(&$form, &$form_state, $form_id){
  //dsm($form);
  // $form['account']['#title'] = t('Create an account');
  $form['customtext_1'] = array(
    '#type' => 'item',
    '#markup' => '<div ><label>It&apos;s free and always will be.</label></div>',
    '#weight' => -1, // Adjust so that you can place it whereever
  );

  $form['account']['pass']['#type'] = 'password';
  $form['account']['pass']['#title'] = 'Password';

  $form['customtext_2'] =array(
    '#type' =>'item',
    '#markup' => '<div><label><a href="#">Why do I need to provide <span class ="span-display">my date of birth?</span></a></label></div>',
    '#weight' => 3,
  );

  $form['customtext_3'] =array(
    '#type' =>'item',
    '#markup' => '<div class="content">By clicking Create an account, you agree to our <a href="#">Terms</a> and confirm <span class="span-display">that you have read our <a href="#">Data Policy</a>, including our <a href="#">Cookie</a> <a href="#">Use </a></span><a href="#">Policy</a>.You may receive SMS message notifications from<span class="span-display"> Facebook and can optout at any time.</span></div>',
    '#weight' => 10,
  );

  $form['customtext_4'] =array(
    '#type' =>'item',
    '#markup' => '<div><p class="content-bold"><a href="#">Create a Page</a> for a celebrity, band or business.</p></div>',
    '#weight' => 110,
  );
  //  $form['field_first_name']['#title_display'] = 'invisible';
  $form['field_first_name']['#prefix'] = '<div class="first">';
  $form['field_first_name']['#suffix'] = '</div>';
  $form['field_surname']['#prefix'] = '<div class="last">';
  $form['field_surname']['#suffix'] = '</div><div class ="clearfix"></div>';

  $form['field_account_gender'][LANGUAGE_NONE]['#title_display'] = 'invisible';
  $form['field_account_birthday'][LANGUAGE_NONE]['#title_display'] = 'invisible';

  $form['actions']['submit']['#value'] = t('Create an account');
}
